[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs",
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php -S 0.0.0.0:$PORT -t public"
