[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction --ignore-platform-reqs",
    "mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache",
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public public/index.php"
