[phases.setup]
nixPkgs = ["php83", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
